### ISSUE TITLE
리스트를 삭제할 때 인덱스가 비는 상황에 대해서

### ISSUE THREAD

**Issue by zionhann** [22000546/2021OSSL_TeamProject#10]
구조체를 정의할 때 연결리스트를 사용하면
중간 리스트를 삭제했을 때 해당 인덱스가 비어 버리는 상황을 막을 수 있을 것 같아요.

예를 들어

1 A
2 B
3 C

에서 2번을 삭제할 경우

1 A
3 C
로 남게 되는 (사소한) 문제요.

아래는 연결리스트 소스코드입니다.
```
typedef struct listNode{
    char name[20]; // 과목 이름
    int type; // 과목 유형(전공:1, 교양:2)
    int credit; // 학점(2학점, 3학점 등)
    char score[3]; // 평점(A0, B+ 등)
    Node* next;
}Node;
```

이 경우도 한번 고려해보면 좋겠네요.

**Comment by 22000546** [comment]
좋아요! 연결리스트로 코드 수정해볼까요 ?

**Comment by zionhann** [comment]
네 해보죠!
