### ISSUE TITLE
linked lists를 이용한 함수 구현

### ISSUE THREAD

**Issue by 22000546** [22000546/2021OSSL_TeamProject#11]
## 구조체 정의 
~~~
typedef struct listNode{
    char name[20]; // 과목 이름
    int type; // 과목 유형(전공:1, 교양:2)
    int credit; // 학점(2학점, 3학점 등)
    char score[3]; // 평점(A0, B+ 등)
    Node* next;
}Node;
~~~

### CRUD 함수
1. create : 
2. read : link를 따라가며 read
3. update : 리스트 보여주고 이름으로 update
4. delete : 리스트 보여주고 이름으로 delete -> link 수정

### 검색 함수
1. searchName : link를 따라가며 주어진 이름과 같은 node 출력
2. searchCredit : link를 따라가며 주어진 학점과 같은 node 출력 -> 여러 개의 node 출력 필요
3. searchGrade : link를 따라가며 주어진 평점과 같은 node 출력 -> 여러 개의 node 출력 필요

### 계산 함수
1. calculateTotalGrade : link를 따라가며 모든 node의 평점을 계산
2. calculateMajorGrade : link를 따라가며 type == 1인 node의 평점을 계산
3. calculateElectiveGrade : link를 따라가며 type == 2인 node의 평점을 계산

\+ 문자열로 받은 평점을 숫자로 변환하는 함수? => 숫자 평점 저장 or 필요할 때 call

**Comment by zionhann** [comment]
> CRUD 함수
create :
read : link를 따라가며 read
update : 리스트 보여주고 이름으로 update
delete : 리스트 보여주고 이름으로 delete -> link 수정

1 A <-HEAD
2 B
3 C

에서 3번을 삭제한다고 할 때 노드를 2번 이동해서  `free()`하면 번호로도 수정하거나 삭제할 수 있을 것 같아요!
```
deleteCourse(Node* course, int index) {
  ...
  for(int i=0; i< index -1; ++i) {
   ...
  }
}

**Comment by zionhann** [comment]
목록을 보여주고 사용자에게 번호를 입력 받는 함수가 추가로 필요할 것 같네요.
main 함수에서 `update`, `delete` 함수 호출하기 전에 번호 입력 받고 `index`를 `argument`로 같이 넘겨주면 될 것 같아요.

**Comment by 22000546** [comment]
네 listCourse 함수 추가로 구현하면 될 것 같아요!

**Comment by 22000546** [comment]
+ 백분율 환산 점수 계산 기능 추가 
(calculateScore(float grade)) : 소숫점 형태로 주어진 평점을 백분율 환산 점수(100-0)로 계산

백분위 환산이 이 기능 의미하는거 맞는지 확인해주세요!

**Comment by zionhann** [comment]
네 맞아요 4.5 평점 기준으로 백분위 환산하는 공식이 있는 것 같은데...

**Comment by 22000546** [comment]
![image](https://user-images.githubusercontent.com/82192913/116949672-ec688000-acbd-11eb-9ee0-da836c2ad6a7.png)
