### ISSUE TITLE
메인 함수 개발 영역 분리 및 함수 구현시 고려할 점

### ISSUE THREAD

**Issue by zionhann** [22000546/2021OSSL_TeamProject#13]
```
int main(void)
{
  // 공동 개발 영역
  // 변수 선언
  Node* head = NULL;
  int menu;
  
  // 단독 개발 영역
  switch(menu) {

  // CRUD, FILE I/O, EXIT ... : case : 0 ~ 6 or more
  case 0 :
    EXIT();
  case 1 :
    CREATE();
  ...
  // SEARCH, CALCULATION ... : case : 7 ~ 8 or more
  case 7 :
    // selectSearchOption();
    SEARCH();
  case 8 :
    CALCULATION();
  ...
   }
}
```

**고려해볼 점들**
1. SEARCH 함수
- 함수 포인터를 사용해서 하나의 함수로 여러 검색이 가능한가?
2. CALCULATION 함수
- 계산결과를 한번에 모두 출력할 것인가?
- 사용자의 선택에 따라서 특정 결과만 보여줄 것인가?
3. FILE LOAD함수
- 프로그램 최초 실행시 자동으로 호출할 것인가?
- 메뉴에 따로 두어서 사용자가 원할 때 불러올 수 있도록 할 것인가?

**Comment by 22000546** [comment]
1. 함수 포인터 내용은 제가 잘 몰라서 단독으로만 구현하기는 힘들 것 같고요. ㅠㅠ
일단 공부해서 두 가지 버전으로 최대한 구현해보도록 할게요!

2. 원하는 계산 결과를 보여주도록 하는 함수 추가 구현하도록 하겠습니다.
    대신 전체 평점평균은 필수로 들어가도록 하는게 좋을 것 같아요!
~~~ 
calculate() : 
   전체 계산 함수의 인터페이스 함수
   전공 평점평균 / 교양 평점평균 / 전체 평점평균 / 백분위 환산 점수 중 원하는 결과를 선택하도록 하는 함수
   선택한 결과를 바탕으로 CALCULATION 함수를 call

   결과 화면 예시) 
   전체 학점 수 / 취득 학점 수 / 전체평점평균 / 환산점수 / 전공평점평균 / 교양평점평균
   전체 학점 수 / 취득 학점 수 / 전공평점평균 
~~~   
~~~
pickCalculationMode() : 
    전공 / 교양 / 전체 평점평균에 대해 모드 선택
    예시)  포함 안함 : 0, 포함함 : 1
~~~
3. 저는 최초 실행시 자동으로 load하는 것이 좋을 것 같다고 생각하는데 어떻게 생각하시는지 알려주세요!

**Comment by zionhann** [comment]
3. 최초 실행시 Load와 case 두 버전 모두 고려해볼게요. 우선 따로 기능을 만드는 걸로 구현할테니  테스트해보시고  리뷰 부탁 드립니다!!
