### ISSUE TITLE
manager.c 링크 오류

### ISSUE THREAD

**Issue by zionhann** [22000546/2021OSSL_TeamProject#17]
manager.c 소스파일과 같이 빌드하는데 다음과 같이 오류가 발생했어요.
컴파일은 잘 되는데 링크 과정에서 문제가 있는 것 같아요.

![210507error](https://user-images.githubusercontent.com/45687157/117334820-6aeb3a80-aed5-11eb-9f3f-b37cb41fe1b3.png)

제 생각에는 `manager.c` 소스파일의 `calculate` 함수에서   

`printToTalGrade`
`printMajorGrade`
`printElectiveGrade`
`printScore`

위 네 함수가 호출은 되고 있는데 함수를 정의한 부분이 없어서 발생한 문제 같아요.
(`manager.h` 헤더파일에는 함수가 잘 선언되어 있는 것을 확인했습니다.)

```
void calculate(Node* course) {
  int mode = pickCalculationMode();

  printToTalGrade();
  if(mode / 100 == 1)
    printMajorGrade(course);
  if(mode / 10 == 1)
    printElectiveGrade(course);
  if(mode / 1 == 1)
    printScore(course);
}
```

**Comment by zionhann** [comment]
`manager.c` 소스파일도 같이 빌드할 수 있게 `Makefile` 업데이트할테니  함수 구현하시고 나서 시간 되실 때 `make` 명령어 사용해서 빌드 되는지 한번 확인 부탁드립니다~~

**Comment by 22000546** [comment]
빌드는 되는데 한글 인코딩 방식이 달라 깨지네요..

**Comment by 22000546** [comment]
혹시 개발환경이 어떻게 되시나요? 저는 euc-kr이 깨지고 UTF-8 이 잘 보입니다. ㅜㅜ 서로 달라서 그런가 하고 다 EUC-KR로 바꿔봤는데 똑같네요. 제가 utf-8로 인코딩해서 올리면 로컬에서 다 깨지시나요? 그러면 그냥 euc-kr로 통일할게요 !

**Comment by zionhann** [comment]
최근에 pull하신거 한글 깨졌었나요? 제가 PR 보낸 것도 EUC-KR로 인코딩한 걸로 알고 있습니다만...
저번에 메인 소스 파일 올리신 게 한글이 깨졌었어요!
인코딩 선택하실 때 `Reopen with encoding` 하지 마시고 `Save with encoding`으로 해보시겠어요?

**Comment by 22000546** [comment]
제가 소스는 다 보이는데 터미널에서만 깨지는 거라.. 일단 해결했습니다~! 그냥 euc-kr로 진행하면 될 것 같아요!

**Comment by zionhann** [comment]
안되거나 어려운 점 있으시면 issue에 올려주세요 같이 고민해봐요~~

**Comment by zionhann** [comment]
해결 확인했어요! 감사합니다:)
