### ISSUE TITLE
주제 정하기

### ISSUE THREAD

**Issue by 22000546** [22000546/2021OSSL_TeamProject#2]
- [ ] 전화번호부
- [x] 학점계산기

**Comment by zionhann** [comment]
1. 전공 평점 평균
2. 교양 평점 평균
3. 전체 평점 평균
4. 백분위 환산
---
| A+ | A0 | B+ | B0 | C+| C0 | D+| D0 | F |
|:----:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 4.5 | 4.0 | 3.5 | 3.0 | 2.5 | 2.0 | 1.5 | 1.0 | 0 |
