### ISSUE TITLE
홈 메뉴 인터페이스에 대한 의견

### ISSUE THREAD

**Issue by zionhann** [22000546/2021OSSL_TeamProject#21]
```
        printf("1. 강의 추가하기\n");
        printf("2. 추가한 강의 보기\n");
        printf("3. 강의 수정하기\n");
        printf("4. 강의 삭제하기\n");
        printf("5. 강의 목록 저장하기\n");
```
`강의 목록 수정하기`
`강의 수정하기`
`목록 수정하기`
뭐가 좋을지 잘 모르겠어요.. 어떤 문장이 잘 어울리나요?

**Comment by 22000546** [comment]
`강의 정보 수정하기`는 어떨까요?
그리고 함수 순서를 바꾸면 어떨까 싶은데 어떻게 생각하시나요
`CRUD -> 계산 -> 검색 -> File IO` 처럼 함수 구현하는 순서대로요!

**Comment by zionhann** [comment]
의견 감사해요!

좋아요! 메인 함수 다 작업하셨나요? 충돌일어날 수 있으니 작업 끝나고 제가 case별로 말씀하신 순서로 다시 정리하겠습니다!

**Comment by zionhann** [comment]
0. 종료
1. 추가
2. 보기
3. 수정
4. 삭제
5. 계산
6. 검색
7. 저장
8. 불러오기

맞나요?
`검색` 함수가 1, 2, 3 다 나눠져있나요?

**Comment by 22000546** [comment]
검색함수 나눠져 있는데 통합해서 제가 메인 수정하겠습니다!
