### ISSUE TITLE
함수 기능 구현

### ISSUE THREAD

**Issue by zionhann** [22000546/2021OSSL_TeamProject#3]
- [x] 프로그램 종료
- [x] CREATE 과목 추가: (1)과목 이름, (2)학점 // 이수 학기, 전공/교양 여부 등등
- [x] READ 과목 조회 : 추가한 과목 조회 
- [x] UPDATE 추가한 과목 수정 : 이름, 학점
- [x] DELETE 학점 삭제
- [x] 파일 저장 : 추가한 학점을 텍스트 파일에 저장
- [x] 파일 불러오기 : 텍스트 파일에 저장된 내용을 불러오기
- [x] 검색1 : 이름 기준으로 검색, 
- [x] 검색2 : 학점 기준으로 검색
- [x] 검색3 : 평점 기준으로 검색
- [x] 계산1 : 전체 평균 평점 계산
- [x] 계산2 : 전공 평균 평점 계산
- [x] 계산3 : 교양 평균 평점 계산

**Comment by 22000546** [comment]
# 함수 내용
## Structure
수업명 수업학점 평점
ex) OSSL 2 A0
## CRUD
1. createScore : "수업명 과목학점 평점"을 입력 값으로 받아 데이터를 저장하는 함수
2. readScore : "수업명 과목학점 평점"을 프린트하는 함수
3. updateScore : 학점 내용을 업데이트하는 함수
4. deleteScore : 학점 내용을 삭제하는 함수
## fileIO
1. saveData : 현재 데이터를 파일로 저장하는 함수
2. loadData : 파일의 데이터를 불러오는 함수
## 검색
1. searchName : 과목명으로 검색 
ex) "프로그래밍"이 들어가는 수업의 데이터 찾기
2. searchCredit : 학점 수로 검색
ex) "3학점인 수업의 데이터 찾기
3. searchGrade : 받은 평점으로 찾기
ex) B+인 수업의 데이터 찾기
## 계산
1. calculateTotalGrade : 주어진 데이터로 전체 성적 계산
