### ISSUE TITLE
헤더파일 내용 확인

### ISSUE THREAD

**Issue by zionhann** [22000546/2021OSSL_TeamProject#4]
# 구조체
* 과목명
* 학점수
* 평점
* 교양/전공
---------------------------------
# 함수 정의
  - [x] CRUD
  - [x] FILE I/O
  - [x] 검색
  - [x] 계산
  - [x] 메뉴
----------------------------------
# 기타
- [x] 헤더파일 중복 방지

**Comment by 22000546** [comment]
## 구조체
평점을 어떻게 받을 것인가 ? (4.5 / A+)
➡️ A+ 형식으로 (문자열)
➡️ 문자열 -> 실수 전환 함수 따로 구현 ?

**Comment by zionhann** [comment]
1. 소문자를 받은 경우 대문자로 변환하고
2. 첫번째 배열 인덱스에서 A, B, C, D, F 이외의 문자를 입력 받은 경우 예외 처리
3. 두번째 배열 인덱스
- +, 0 이외의 문자 입력받은 경우 예외처리
- 비어 있는 경우 (예를 들어 B만 입력한 경우) 0 추가
